import React from 'react';
import { 
  Fingerprint, Target, Zap, Shield, Cpu, 
  MessageSquare, Layers, Search, Globe, 
  Terminal, History, Radio, Eye, Activity
} from 'lucide-react';
import { DocumentWatermark, SectionHeader, DocCard, TechLabel, TechNote, ClauseFrame } from './DocHelpers';

export const IdentityManifestContent = () => (
  <div className="space-y-0 pb-40 max-w-6xl mx-auto selection:bg-cyan-500/20 relative">
    <DocumentWatermark text="BRAND_DNA_MANIFEST" />
    
    <SectionHeader 
      id="DOC: VIG-DNA-2026.01"
      category="Strategic Branding Unit"
      title="Identity Manifest."
      subtitle="The Genetic Code of the Sovereign Security Standard"
      colorClass="text-cyan-500"
      bgGlow="bg-cyan-600/10"
    />

    <div className="space-y-20 px-6 md:px-12 relative z-10">
      
      {/* 1. CORE MISSION */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 01: CORE MISSION" color="cyan" />
        <DocCard border="cyan" glow>
          <div className="space-y-6">
            <h3 className="text-2xl font-black text-white italic uppercase tracking-tight">The Intent Validator</h3>
            <p className="text-zinc-400 text-lg leading-relaxed font-medium">
              VIGIL's mission is to secure the <span className="text-white">Human-Layer (Layer 0.5)</span>. We solve the problem of **Cognitive Deception**—specifically address poisoning and visual homograph attacks—where the blockchain is secure but the user's perception is compromised.
            </p>
            <TechNote title="THE PROBLEM">
              Adversaries exploit the 8-character verification gap (4 prefix + 4 suffix). VIGIL restores context inside the DOM before a transaction reaches the signature phase.
            </TechNote>
          </div>
        </DocCard>
      </section>

      {/* 2. TARGET AUDIENCE */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 02: TARGET AUDIENCE" color="blue" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <DocCard border="zinc">
            <h4 className="text-white font-black uppercase tracking-widest text-xs mb-4">High-Value Operators</h4>
            <p className="text-zinc-500 text-sm leading-relaxed italic">Whales, Treasury managers, and institutional traders for whom a single character error equals catastrophic asset loss.</p>
          </DocCard>
          <DocCard border="zinc">
            <h4 className="text-white font-black uppercase tracking-widest text-xs mb-4">Sovereign Individuals</h4>
            <p className="text-zinc-500 text-sm leading-relaxed italic">Privacy-focused Web3 users who refuse cloud-based surveillance and demand local-first security primitives.</p>
          </DocCard>
        </div>
      </section>

      {/* 3. GOALS & VALUES */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 03: BRAND VALUES" color="emerald" />
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
           {[
             { t: "Privacy Absolute", d: "Zero-knowledge localized processing. Your history never leaves your browser.", i: <Shield size={18} /> },
             { t: "Radical Transparency", d: "Open-source heuristics. Verifiable security logic.", i: <Search size={18} /> },
             { t: "Non-Invasive", d: "Vigilance without surveillance. No behavioral tracking.", i: <Eye size={18} /> }
           ].map((v, i) => (
             <div key={i} className="p-8 bg-zinc-950 border border-zinc-900 rounded-3xl space-y-4 group hover:border-emerald-500/30 transition-all">
                <div className="text-emerald-500 group-hover:scale-110 transition-transform">{v.i}</div>
                <h5 className="text-white font-black uppercase tracking-tighter italic">{v.t}</h5>
                <p className="text-zinc-600 text-[11px] font-bold uppercase leading-relaxed">{v.d}</p>
             </div>
           ))}
        </div>
      </section>

      {/* 4. COMPETITIVE LANDSCAPE */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 04: COMPETITIVE DIFFERENTIATION" color="blue" />
        <ClauseFrame id="VIG-DIFF-01">
          <h4 className="text-lg font-black text-white italic uppercase">Beyond the Wallet</h4>
          <p className="text-zinc-400 font-medium leading-relaxed">
            Unlike MetaMask or Ledger which operate at the **Execution Layer (L1)**, VIGIL operates at the **Intent Layer (L0.5)**. We identify threats *before* the "Sign" prompt is even generated by monitoring the discovery environment (Social, Explorers, Docs).
          </p>
        </ClauseFrame>
      </section>

      {/* 5. VISUAL STYLE */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 05: AESTHETIC STANDARD" color="cyan" />
        <DocCard border="cyan">
           <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
              <div className="space-y-6">
                 <h4 className="text-4xl font-black text-white italic uppercase tracking-tighter">Sovereign <br/> Tactical.</h4>
                 <p className="text-zinc-500 text-sm leading-relaxed italic">Minimalist, professional infrastructure aesthetic. Industrial security grade.</p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                 <div className="p-4 bg-[#050505] border border-zinc-800 rounded-xl text-center">
                    <div className="text-[10px] font-black text-zinc-600 uppercase mb-2">Primary</div>
                    <div className="w-full h-8 bg-white rounded" />
                 </div>
                 <div className="p-4 bg-[#050505] border border-zinc-800 rounded-xl text-center">
                    <div className="text-[10px] font-black text-zinc-600 uppercase mb-2">Accent</div>
                    <div className="w-full h-8 bg-blue-600 rounded" />
                 </div>
              </div>
           </div>
        </DocCard>
      </section>

      {/* 6. TAGLINE */}
      <section className="space-y-8 text-center py-10">
        <TechLabel text="SECTOR 06: CORE MESSAGING" color="blue" />
        <h2 className="text-5xl md:text-6xl font-black text-white italic uppercase tracking-tighter">
          Vigilance is the only <br/> permanent shield.
        </h2>
        <p className="text-zinc-600 font-mono text-xs uppercase tracking-[0.5em]">SECURE THE INTENT LAYER</p>
      </section>

      {/* 7. EXISTING ASSETS */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 07: REGISTERED ASSETS" color="zinc" />
        <div className="p-10 bg-zinc-950 border border-zinc-900 rounded-[3rem] flex items-center justify-between">
           <div className="space-y-4">
              <h4 className="text-xl font-black text-white italic uppercase">The Sentinel Apex</h4>
              <p className="text-zinc-500 text-xs font-bold uppercase tracking-widest leading-relaxed">
                Primary Identity Mark: A geometric abstraction of the 0.5 bridge. <br/>
                Colorway: White on Zinc.
              </p>
           </div>
           <div className="w-20 h-20 bg-white flex items-center justify-center rounded-xl shadow-2xl">
              <div className="w-10 h-10 bg-black rotate-45" />
           </div>
        </div>
      </section>

      {/* 8. TONE & VOICE */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 08: VOICE SPECIFICATION" color="red" />
        <DocCard border="red">
           <ul className="space-y-6">
              {[
                { t: "Authoritative", d: "Speaking from the position of foundational technical truth." },
                { t: "Precise", d: "No fluff. Deliverables only. Scientific telemetry over marketing hype." },
                { t: "Definitive", d: "Presenting VIGIL not as an option, but as the new industry standard." }
              ].map((v, i) => (
                <li key={i} className="flex gap-6 items-start">
                   <div className="w-1.5 h-1.5 rounded-full bg-red-600 mt-2 shrink-0" />
                   <div className="space-y-1">
                      <h5 className="text-[12px] font-black text-white uppercase tracking-widest">{v.t}</h5>
                      <p className="text-[11px] text-zinc-500 font-bold uppercase tracking-tight italic">{v.d}</p>
                   </div>
                </li>
              ))}
           </ul>
        </DocCard>
      </section>

      {/* 9. SCOPE & TIMELINE */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 09: OPERATIONAL SCOPE" color="cyan" />
        <div className="p-8 bg-zinc-900/30 border border-zinc-800 rounded-3xl flex items-center gap-8">
           <Radio className="w-10 h-10 text-cyan-500 animate-pulse shrink-0" />
           <p className="text-zinc-400 text-sm leading-relaxed font-medium italic">
             Phase 1: Brand consolidation and social deployment. <br/>
             Phase 2: Field Unit beta manifestation. <br/>
             Phase 3: Global Mesh Synchronization.
           </p>
        </div>
      </section>

      {/* 10. INSPIRATIONS */}
      <section className="space-y-8">
        <TechLabel text="SECTOR 10: STRATEGIC INSPIRATIONS" color="zinc" />
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
           {['Signal', 'Bell Labs', 'Lockheed Martin', 'Chainlink'].map(insp => (
             <div key={insp} className="p-6 bg-zinc-950 border border-zinc-900 rounded-2xl text-center">
                <div className="text-[9px] font-black text-zinc-700 uppercase tracking-[0.4em] mb-1">REFERENCE</div>
                <div className="text-[11px] font-black text-zinc-300 uppercase">{insp}</div>
             </div>
           ))}
        </div>
      </section>

      <div className="pt-24 text-center space-y-8">
         <div className="h-[2px] w-24 bg-cyan-900/30 mx-auto" />
         <h3 className="text-3xl font-black text-white italic uppercase tracking-[0.3em]">End of DNA Manifest</h3>
         <p className="text-[9px] font-black text-zinc-700 uppercase tracking-[0.5em]">Authored for: GROK Intelligence Node</p>
      </div>
    </div>
  </div>
);